language: python

python:
    - 2.7
    - 3.0
    - 3.1
    - 3.2
    - 3.3
    - 3.4
    
install: "pip install -r requirements.txt"

script:
 - python test.py
 
notifications:
  email: 
    - adam@sf2.guru